name: LiteCosmetics
version: '${project.version}'
main: dev.etery.litecosmetics.LiteCosmeticsPlugin
depend:
  - "LiteCoin"
commands:
  shop:
    usage: /shop
    description: shopping
  test:
    usage: /test
    description: testing