name: LiteCosmetics
version: '${project.version}'
main: dev.etery.litecosmetics.LiteCosmeticsPlugin
depend:
  - "LiteCoin"
commands:
  taunt:
    usage: /taunt
    description: taunting
  shop:
    usage: /shop
    description: shopping